---
- name: Make app directory
  become: true
  file: path=/var/www state=directory mode=0755

- name: Symbolic link
  become: true
  file: src=/vagrant dest=/var/www/vhosts state=link

- name: Set authorized key taken from file
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/Users/junkang/.ssh/id_rsa.pub') }}"

- name: Install basic packages
  become: true
  yum:
    pkg:
      - git
      - unzip
      - java-1.8.0-openjdk-1.8.0.222.b10
    state: present
    update_cache: yes
